build-and-test:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk add --no-cache docker-compose curl go
  script:
    - go install github.com/rakyll/hey@latest
    - cd openresty-slo && docker-compose up --no-deps --detach --wait
    - curl -i http://localhost:8888
    - ~/go/bin/hey http://localhost:8888
