build-and-test:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk add --no-cache docker-compose curl go
  script:
    - go install github.com/rakyll/hey@latest
    - cd openresty-slo && docker-compose up --detach --wait --quiet-pull
    - until curl -is http://localhost:8888 > /dev/null; do echo "Waiting for service..."; sleep 5; done
    - ~/go/bin/hey http://localhost:8888
